stages:
  invalidate:
    cmd: python stages/00_invalidate.py
    deps:
      - stages/00_invalidate.py
    outs:
      - cache/00_invalidate
  download: 
    cmd: stages/01_download.sh
    deps:
      - cache/00_invalidate
      - stages/01_download.sh
    outs:
      - cache/01_download
  build: 
    cmd: python stages/03_build.py
    deps:
      - stages/03_build.py
      - cache/01_download
    outs:
      - brick
